# Generated by Django 4.2.5 on 2023-09-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='exemplosenha', max_length=200),
            preserve_default=False,
        ),
    ]
