# Generated by Django 4.2.5 on 2023-10-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0003_usuario_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
