# Generated by Django 4.2.5 on 2023-10-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0005_rename_nome_pessoa_email_remove_pessoa_idade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='nome',
            field=models.TextField(default='nome', max_length=255),
            preserve_default=False,
        ),
    ]
