# Generated by Django 4.2.5 on 2023-10-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0007_pessoa_atualizado_pessoa_criado_pessoa_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
