# Generated by Django 4.2.5 on 2023-10-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0008_grupo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
