# Generated by Django 4.2.5 on 2023-10-02 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0010_grupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='descricao',
            new_name='descricao_grupo',
        ),
        migrations.RenameField(
            model_name='grupo',
            old_name='nome',
            new_name='nome_grupo',
        ),
    ]
