# Generated by Django 4.2.5 on 2023-10-02 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0011_rename_descricao_grupo_descricao_grupo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
