# Generated by Django 4.2.5 on 2023-10-03 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0013_grupo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
