# Generated by Django 4.2.5 on 2023-10-03 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0016_alter_grupo_descricao_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='criador',
            field=models.ForeignKey(default='usuario', on_delete=django.db.models.deletion.CASCADE, to='ccapp.pessoa'),
            preserve_default=False,
        ),
    ]
