# Generated by Django 4.2 on 2023-11-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0017_delete_perfil_delete_usuario_pessoa_grupo_criado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='curso',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='mbti',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='periodo',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
