# Generated by Django 4.2 on 2023-11-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0018_pessoa_curso_pessoa_foto_pessoa_idade_pessoa_mbti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='foto_grupo',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
