# Generated by Django 4.2 on 2023-11-03 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0019_grupo_foto_grupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='periodo',
            new_name='periodo_grupo',
        ),
    ]
